### PR TITLE
Don't run mirgecom downstream CI in parallel

### PR DESCRIPTION
**Pull request by inducer**
Potentially address #211.

cc @thomasgibson

### CODE REVIEW

**Comment by inducer** [comment]
Meshmode does the same and has never had an issue, FWIW:

https://github.com/inducer/meshmode/blob/19ad308ee95e3ce78b9928620e5177fb1de08cfc/.ci/install-downstream.sh#L27

**Comment by inducer** [comment]
@matthiasdiener I don't fully recall. Is mirgecom expected to pass CI with pytest running parallel?

**Review by thomasgibson — APPROVED** [review]
LGTM! If it works for meshmode, then I think it's fine for grudge to do the same

**Comment by matthiasdiener** [comment]
> @matthiasdiener I don't fully recall. Is mirgecom expected to pass CI with pytest running parallel?

I think it is expected to pass, but sometimes runs into memory issues if I remember correctly.

**Pull request merged**
