### PR TITLE
fix flake8 CI

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by majosm** [comment]
Strange that it's only occurring on CI though? I haven't been able to reproduce it locally (even after updating flake8).

**Comment by kaushikcfd** [comment]
> Strange that it's only occurring on CI though? I haven't been able to reproduce it locally (even after updating flake8).

`flake8-bugbear` got a release couple of days ago: https://pypi.org/project/flake8-bugbear/#history. Could you try: `pip install --upgrade flake8-bugbear`?

**Comment by majosm** [comment]
> `flake8-bugbear` got a release couple of days ago: https://pypi.org/project/flake8-bugbear/#history. Could you try: `pip install --upgrade flake8-bugbear`?

Ah, yeah that did it.

**Review by kaushikcfd — APPROVED** [review]
LGTM, thanks!

**Comment by matthiasdiener** [comment]
> I think the following diff should resolve it:
> 
> ```diff
> diff --git a/examples/old_symbolics/dagrt-fusion.py b/examples/old_symbolics/dagrt-fusion.py
> index c431e21..6ba4803 100755
> --- a/examples/old_symbolics/dagrt-fusion.py
> +++ b/examples/old_symbolics/dagrt-fusion.py
> @@ -243,7 +243,7 @@ def isolate_function_calls_in_phase(phase, stmt_id_gen, var_name_gen):
>              stmt_id_gen=stmt_id_gen,
>              var_name_gen=var_name_gen)
>  
> -    for stmt in sorted(phase.statements, key=lambda stmt: stmt.id):
> +    for stmt in sorted(phase.statements, key=lambda stmt_: stmt_.id):
>          new_deps = []
>  
>          from dagrt.language import Assign
> ```

Thanks, that suggestion was simpler than what I had in mind ;-)

**Comment by matthiasdiener** [comment]
> > Strange that it's only occurring on CI though? I haven't been able to reproduce it locally (even after updating flake8).
> 
> `flake8-bugbear` got a release couple of days ago: https://pypi.org/project/flake8-bugbear/#history. Could you try: `pip install --upgrade flake8-bugbear`?

Side note: The number of Stackoverflow answers on how to upgrade all pip packages is just amazing: https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip

**Pull request merged**
