### PR TITLE
Pytato array context

### PR DESCRIPTION
**Pull request by inducer**
This serves as a focal point towards getting grudge-based simulations going on the https://github.com/inducer/pytato/ lazy array. In terms of a development model, I propose we use PRs into this branch.

Relies on the following (draft until these are merged):

- [x] https://github.com/inducer/loopy/pull/222 (alias of https://github.com/inducer/loopy/tree/pytato_array_context)
- [x] https://github.com/inducer/pytato/pull/20 (alias of https://github.com/kaushikcfd/pytato/tree/pytato_array_context)
- [x] ~~https://github.com/inducer/meshmode/pull/116~~ https://github.com/inducer/meshmode/pull/216

Draft until:

- [x] `requirements.txt` pointed back at master for all dependencies
- [ ] Downstream tests of mirgecom are added, passing (cf. #44)

cc @matthiasdiener @kaushikcfd @lukeolson

### CODE REVIEW

**Comment by kaushikcfd** [comment]
[These lines](https://github.com/inducer/grudge/blob/23452b1796debee19a0de50c927884b951c8bf23/grudge/execution.py#L543-L549) must be rewritten in order to remove stateful array uses.
- `result` should not be passed in, instead the result per group should be stored to an array and `DoFArray.from_list` must be invoked on the per-group results.
- Should have the line `nelements=grp.nelements`.

**Comment by matthiasdiener** [comment]
I don't have permissions to modify this PR :-(

**Comment by matthiasdiener** [comment]
Can this PR be closed now?

**Comment by kaushikcfd** [comment]
> Can this PR be closed now?

Yep!

**Pull request closed without merging**
