### PR TITLE
discretization: use part_id instead of removed part_nr

### PR DESCRIPTION
**Pull request by alexfikl**
Missed this when working on inducer/meshmode#396.

### CODE REVIEW

**Comment by inducer** [comment]
Thx!

**Comment by inducer** [comment]
Out of curiosity: how come the downstream test didn't flag this?

**Comment by alexfikl** [comment]
> Out of curiosity: how come the downstream test didn't flag this?

Hm, seems to be in `distributed_boundary_swap_connection`.. Do the tests not call that or does the upstream run not use MPI?

**Comment by inducer** [comment]
MPI gets turned off for downstream: https://github.com/inducer/ci-support/blob/f2a4fff5ebfb7e37b0eb1e40371471d76f084ced/ci-support.sh#L818

**Comment by inducer** [comment]
So no mystery here. Thanks for looking... I feel like I could've answered that myself. :grimacing: Sorry!

**Pull request merged**
