### PR TITLE
Add caching to batched diff

### PR DESCRIPTION
**Pull request by nchristensen**

### CODE REVIEW

**Comment by nchristensen** [comment]
For some reason I can't see the test logs. "We are currently unable to download the log. Please try again later."

**Comment by inducer** [comment]
I can see them:
```
_ test_tri_diff_mat[<array context factory for <pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz' on 'Portable Computing Language'>-3] _
[gw2] linux -- Python 3.8.5 /home/runner/work/grudge/grudge/.miniforge3/envs/testing/bin/python3
Traceback (most recent call last):
  File "/home/runner/work/grudge/grudge/test/test_grudge.py", line 447, in test_tri_diff_mat
    assert eoc_rec.order_estimate() > order
AssertionError: assert -3.381765231540588e-05 > 4
 +  where -3.381765231540588e-05 = <bound method EOCRecorder.order_estimate of <pytools.convergence.EOCRecorder object at 0x7f7bacb96610>>()
 +    where <bound method EOCRecorder.order_estimate of <pytools.convergence.EOCRecorder object at 0x7f7bacb96610>> = <pytools.convergence.EOCRecorder object at 0x7f7bacb96610>.order_estimate
_ test_surface_divergence_theorem[<array context factory for <pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz' on 'Portable Computing Language'>-spheroid] _
[gw2] linux -- Python 3.8.5 /home/runner/work/grudge/grudge/.miniforge3/envs/testing/bin/python3
Traceback (most recent call last):
  File "/home/runner/work/grudge/grudge/test/test_grudge.py", line 611, in test_surface_divergence_theorem
    op_global = bind(discr, sym_op_global)(actx)
  File "/home/runner/work/grudge/grudge/grudge/execution.py", line 673, in __call__
    self.discr_code.execute(
  File "/home/runner/work/grudge/grudge/grudge/symbolic/compiler.py", line 527, in execute
    assignments, new_futures = mapper_method(insn, profile_data)
  File "/home/runner/work/grudge/grudge/grudge/execution.py", line 544, in map_insn_diff_batch_assign
    self.array_context.call_loopy(
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/meshmode/array_context.py", line 319, in call_loopy
    evt, result = program(self.queue, **kwargs, allocator=self.allocator)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/loopy/kernel/__init__.py", line 1455, in __call__
    return kex(*args, **kwargs)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/loopy/target/pyopencl_execution.py", line 363, in __call__
    return kernel_info.invoker(
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/pytools/py_codegen.py", line 152, in __call__
    return self.func(*args, **kwargs)
  File "<generated code>", line 193, in invoke_diff_loopy_kernel
TypeError: shape mismatch on argument 'diff_mat' (got: (2, 15, 15), expected: (1, 15, 15))
_ test_convergence_maxwell[<array context factory for <pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz' on 'Portable Computing Language'>-5] _
[gw0] linux -- Python 3.8.5 /home/runner/work/grudge/grudge/.miniforge3/envs/testing/bin/python3
Traceback (most recent call last):
  File "/home/runner/work/grudge/grudge/test/test_grudge.py", line 853, in test_convergence_maxwell
    for event in dt_stepper.run(t_end=final_t):
  File "<string>", line 292, in run
  File "<string>", line 310, in run_single_step
  File "<string>", line 258, in phase_primary
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py", line 1100, in __rmul__
    result = self._new_like_me(common_dtype)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py", line 950, in _new_like_me
    return self.__class__(queue, self.shape, dtype,
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py", line 536, in __init__
    self.base_data = self.allocator(alloc_nbytes)
pyopencl._cl.MemoryError: create_buffer failed: MEM_OBJECT_ALLOCATION_FAILURE
```

**Comment by nchristensen** [comment]
One problem is that this should be merged to the array_context branch rather than master since this uses the array context. I'll close this and make a new pull request on that branch, but for some reason it still fails the test_tri_diff_mat test.

**Comment by inducer** [comment]
I'm a bit confused. Array context *is* master. It was merged this summer.

**Comment by nchristensen** [comment]
Ah, okay. My dependencies are out of date then.

**Comment by nchristensen** [comment]
Currently fails for test_tri_diff_mat, test_surface_divergence_theorem

```FAILED test_grudge.py::test_tri_diff_mat[<array context factory for <pyopencl.Device 'TITAN V' on 'NVIDIA CUDA'>-3] - assert -3.3817652344126076e-05 > 4
FAILED test_grudge.py::test_tri_diff_mat[<array context factory for <pyopencl.Device 'Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz' on 'Intel(R) CPU Runtime for OpenCL(TM) Applications'>-3] - assert -3.381765234335267e-05 > 4
FAILED test_grudge.py::test_surface_divergence_theorem[<array context factory for <pyopencl.Device 'TITAN V' on 'NVIDIA CUDA'>-spheroid] - TypeError: shape mismatch on argument 'diff_mat' (got: (2, 15, 15), expected: (1, 15, 15))
FAILED test_grudge.py::test_surface_divergence_theorem[<array context factory for <pyopencl.Device 'Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz' on 'Intel(R) CPU Runtime for OpenCL(TM) Applications'>-spheroid] - TypeError: shape mismatch ...
```

**Comment by nchristensen** [comment]
@inducer Can you share the CI / Examples log?

**Comment by inducer** [comment]
Sure:
```
INFO:meshmode.discretization.connection.face:building face restriction: start
INFO:meshmode.discretization.connection.face:building face restriction: done
INFO:meshmode.discretization.connection.face:building face restriction: start
INFO:meshmode.discretization.connection.face:building face restriction: done
Traceback (most recent call last):
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/pytools/__init__.py", line 539, in _deco
    return func._memoize_dic[key]  # pylint: disable=protected-access
KeyError: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dagrt-fusion.py", line 1308, in <module>
    main()
  File "dagrt-fusion.py", line 1303, in main
    scalar_assignment_percent_of_total_mem_ops_table()
  File "dagrt-fusion.py", line 1191, in scalar_assignment_percent_of_total_mem_ops_table
    result3d = mem_ops_results(actx, 3)
  File "<decorator-gen-55>", line 2, in mem_ops_results
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/pytools/__init__.py", line 546, in _deco
    result = func(*args, **kwargs)
  File "dagrt-fusion.py", line 1146, in mem_ops_results
    for (_, _, profile_data) in stepper.run(
  File "dagrt-fusion.py", line 335, in run
    results = self.bound_op(
  File "/home/runner/work/grudge/grudge/grudge/execution.py", line 680, in __call__
    return self.eval_code.execute(
  File "/home/runner/work/grudge/grudge/grudge/symbolic/compiler.py", line 527, in execute
    assignments, new_futures = mapper_method(insn, profile_data)
  File "dagrt-fusion.py", line 630, in map_insn_assign
    result.append((name, self.process_assignment_expr(expr, profile_data)))
  File "dagrt-fusion.py", line 603, in process_assignment_expr
    val = self.map_profiled_call(expr, profile_data)
  File "dagrt-fusion.py", line 566, in map_profiled_call
    return self.inner_mapper.function_registry[expr.function.name](
  File "/home/runner/work/grudge/grudge/grudge/function_registry.py", line 127, in __call__
    return self.implementation(array_context, *args, **kwargs)
  File "dagrt-fusion.py", line 406, in _bound_op
    result = self.grudge_bound_op(
  File "/home/runner/work/grudge/grudge/grudge/execution.py", line 680, in __call__
    return self.eval_code.execute(
  File "/home/runner/work/grudge/grudge/grudge/symbolic/compiler.py", line 527, in execute
    assignments, new_futures = mapper_method(insn, profile_data)
  File "dagrt-fusion.py", line 630, in map_insn_assign
    result.append((name, self.process_assignment_expr(expr, profile_data)))
  File "dagrt-fusion.py", line 615, in process_assignment_expr
    val = self.map_profiled_essentially_elementwise_linear(
  File "dagrt-fusion.py", line 571, in map_profiled_essentially_elementwise_linear
    result = getattr(self.inner_mapper, op.mapper_method)(op, field_expr)
  File "/home/runner/work/grudge/grudge/grudge/execution.py", line 309, in map_projection
    return conn(self.rec(field_expr))
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/meshmode/discretization/connection/direct.py", line 313, in __call__
    result = self.to_discr.empty(actx, dtype=ary.entry_dtype)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/meshmode/discretization/__init__.py", line 255, in empty
    return self._new_array(actx, actx.empty, dtype=dtype)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/meshmode/discretization/__init__.py", line 240, in _new_array
    return _DOFArray.from_list(actx, [
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/meshmode/discretization/__init__.py", line 241, in <listcomp>
    creation_func(shape=(grp.nelements, grp.nunit_dofs), dtype=dtype)
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/meshmode/array_context.py", line 290, in empty
    return cla.empty(self.queue, shape=shape, dtype=dtype,
  File "/home/runner/work/grudge/grudge/.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py", line 533, in __init__
    self.base_data = cl.Buffer(
pyopencl._cl.MemoryError: create_buffer failed: MEM_OBJECT_ALLOCATION_FAILURE
ci-support.sh: line 349:  9244 Segmentation fault      (core dumped) ${PY_EXE} "$bn"
```

**Comment by inducer** [comment]
Btw, could you merge in master to make sure you're using the latest code?

**Comment by nchristensen** [comment]
I can't replicate these failures on Monza (our lab GPU machine). Both dagrt-fusion.py and test_grudge complete with no failures.

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/grudge/-/merge_requests/87

**Comment by inducer** [comment]
cc @matthiasdiener

**Comment by matthiasdiener** [comment]
This error

```
../.miniforge3/envs/testing/lib/python3.8/site-packages/pyopencl/array.py:533: MemoryError
```

might indicate that the memory usage is too big for the CI VMs, in particular if the tests are running fine on your local machine.

**Comment by inducer** [comment]
Initially, I dismissed that possibility, since the change here should not substantially change memory usage. But then it occurred to me that there could be a timing component to this: The change *should* speed up differentiation a bit. Combine that with the fact that we're running the tests in parallel, this could subtly shift the timing and lead to a few "heavy" tests running together. I can also reliably reproduce the failure on my machine after setting
```
ulimit -v 3000000
PYOPENCL_TEST=port python test_grudge.py 'test_convergence_maxwell(acf, 5)' 
```

cc @fischer1

**Comment by inducer** [comment]
I can *also* reproduce the crash in `dagrt-fusion`, but that seems to be something different.

**Comment by inducer** [comment]
c3aaac6

**Comment by nchristensen** [comment]
Still fails :(

**Comment by inducer** [comment]
By now I'm pretty convinced that these are just honest out-of-memory issues. 6361820 might help by turning off some of the bigger memory hogs.

**Comment by inducer** [comment]
Btw passed on Gitlab without a problem, which further supports the OOM theory.

**Comment by inducer** [comment]
:tada:

**Comment by inducer** [comment]
It turns out that this continues to cause mysterious memory problems. Reverting for now: https://github.com/inducer/grudge/pull/21

**Pull request merged**
