### PR TITLE
Docs: Stop linking to source code from docs

### PR DESCRIPTION
**Pull request by inducer**
As of https://github.com/inducer/grudge/pull/74, there might actually be something resembling adequate documentation so that we don't need the sad excuse of "just go look at the source".

@thomasgibson What do you think?

### CODE REVIEW

**Comment by thomasgibson** [comment]
Any reason not to do both?

**Comment by MTCam** [comment]
> Any reason not to do both?

fwiw, i *really* like both, but am not opposed to getting trained off of that.

**Comment by thomasgibson** [comment]
> > Any reason not to do both?
> 
> fwiw, i _really_ like both, but am not opposed to getting trained off of that.

I like both too. I don't really see any reason to drop it. Why not link to the source code for curious readers?

**Comment by inducer** [comment]
:shrug: OK. Nvm then. Thanks for chiming in with your thoughts.

**Pull request closed without merging**
