### PR TITLE
enable SVM args in wave-op-mpi

### PR DESCRIPTION
**Pull request by matthiasdiener**
(not meant for merging)

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This currently fails with:

```
Traceback (most recent call last):
  File "/shared/home/mdiener/Work/emirge/grudge/examples/wave/wave-op-mpi.py", line 334, in <module>
    main(cl.create_some_context,
  File "/shared/home/mdiener/Work/emirge/grudge/examples/wave/wave-op-mpi.py", line 278, in main
    fields = compiled_lsrk45_step(actx, fields, t, dt, compiled_rhs)
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/shortcuts.py", line 54, in compiled_lsrk45_step
    rhs_val = f(t + c*h, y)
  File "/shared/home/mdiener/Work/emirge/grudge/examples/wave/wave-op-mpi.py", line 262, in rhs
    return wave_operator(actx, dcoll, c=c, w=w, quad_tag=quad_tag)
  File "/shared/home/mdiener/Work/emirge/grudge/examples/wave/wave-op-mpi.py", line 130, in wave_operator
    u=-c*op.weak_local_div(dcoll, dd_vol, v),
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/op.py", line 543, in weak_local_div
    return rec_map_subarrays(
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/tools.py", line 363, in rec_map_subarrays
    return map_subarrays(
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/tools.py", line 304, in map_subarrays
    return f(ary)
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/op.py", line 544, in <lambda>
    lambda vec: sum(
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/op.py", line 545, in <genexpr>
    weak_local_d_dx(dcoll, dd_in, i, vec_i)
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/op.py", line 499, in weak_local_d_dx
    return _single_axis_derivative_kernel(
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/op.py", line 179, in _single_axis_derivative_kernel
    data=tuple(
  File "/shared/home/mdiener/Work/emirge/grudge/grudge/op.py", line 181, in <genexpr>
    actx.einsum("rej,rij,ej->ei" if metric_in_matvec else "rei,rij,ej->ei",
  File "/shared/home/mdiener/Work/emirge/arraycontext/arraycontext/context.py", line 471, in einsum
    out_ary = self.call_loopy(
  File "/shared/home/mdiener/Work/emirge/arraycontext/arraycontext/impl/pyopencl/__init__.py", line 269, in call_loopy
    evt, result = t_unit(self.queue, **kwargs, allocator=self.allocator)
  File "/shared/home/mdiener/Work/emirge/loopy/loopy/translation_unit.py", line 347, in __call__
    return pex(*args, **kwargs)
  File "/shared/home/mdiener/Work/emirge/loopy/loopy/target/pyopencl_execution.py", line 388, in __call__
    return translation_unit_info.invoker(
  File "/shared/home/mdiener/Work/emirge/miniforge3/envs/ceesd/lib/python3.9/site-packages/pytools/py_codegen.py", line 150, in __call__
    return self.func(*args, **kwargs)
  File "<generated code for 'invoke_einsum4to2_kernel_loopy_kernel'>", line 221, in invoke_einsum4to2_kernel_loopy_kernel
  File "<generated code for 'invoke_einsum4to2_kernel_loopy_kernel'>", line 33, in _lpy_host_einsum4to2_kernel
AttributeError: 'pyopencl._cl.Buffer' object has no attribute '_ptr_as_int'
```

Not sure if we need to change some other allocators as well @inducer

**Comment by inducer** [comment]
You can monkeypatch the `Buffer` constructor to see where a buffer is being allocated.

**Comment by inducer** [comment]
(I don't see a good reason why there would be any `Buffer`s allocated at all.)

**Comment by matthiasdiener** [comment]
https://github.com/inducer/pyopencl/pull/585 fixes the issue outlined above, and the example runs successfully in eager mode. In lazy mode, there is an additional error due to the use of a `DeferredAllocator` in the generated code, which also allocates a Buffer. Replacing this `DeferredAllocator` with an `SVMAllocator` runs farther, but eventually runs out of memory after some time. I guess we will have to implement the memory pool?

**Comment by inducer** [comment]
It's surprising that you can pass an SVM allocator to a buffer-based memory pool; that's not supposed to work; I don't even knoiw what it's doing in that case. I've been working on the SVM memory pool, but it's a somewhat, especially when doing it "on the side".

**Comment by matthiasdiener** [comment]
Closing this since we use SVM in the mirgecom examples.

**Pull request closed without merging**
