### PR TITLE
Remove make_obj_array([...]) for scalar DOF arrays

### PR DESCRIPTION
**Pull request by majosm**

### CODE REVIEW

**Review by inducer — APPROVED** [review]
Thanks!

**Review by inducer — APPROVED** [review]
Thanks, LGTM! I pointed meshmode back to master. Any other reasons why this is still in draft state/shouldn't be merged yet?

**Comment by majosm** [comment]
Nope, should be good to go I think.

**Comment by inducer** [comment]
Cool. I'll wait for CI and then merge.

**Pull request merged**
